// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RpcBus.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace gRpcBus {

  /// <summary>Holder for reflection information generated from RpcBus.proto</summary>
  public static partial class RpcBusReflection {

    #region Descriptor
    /// <summary>File descriptor for RpcBus.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RpcBusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxScGNCdXMucHJvdG8SCU1zZ1JwY0J1cyLGAQoKQnVzUmVxdWVzdBIMCgRu",
            "YW1lGAEgASgJEg4KBmFjdGl2ZRgCIAEoCRIKCgJpZBgDIAEoBRIPCgdSZXFK",
            "c29uGAQgAygJEhAKCFJlcUJ5dGVzGAUgAygMEi0KBEFyZ3MYBiADKAsyHy5N",
            "c2dScGNCdXMuQnVzUmVxdWVzdC5BcmdzRW50cnkSDwoHdmVyc2lvbhgHIAEo",
            "CRorCglBcmdzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4",
            "ASKzAQoIQnVzUmVwbHkSCgoCaWQYASABKAUSDQoFcmVxaWQYAiABKAUSDwoH",
            "UnNwSnNvbhgDIAMoCRIQCghSc3BCeXRlcxgEIAMoDBIrCgRBcmdzGAUgAygL",
            "Mh0uTXNnUnBjQnVzLkJ1c1JlcGx5LkFyZ3NFbnRyeRIPCgd2ZXJzaW9uGAcg",
            "ASgJGisKCUFyZ3NFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6",
            "AjgBMvcBCgZScGNCdXMSOgoKUmVxdWVzdFNydhIVLk1zZ1JwY0J1cy5CdXNS",
            "ZXF1ZXN0GhMuTXNnUnBjQnVzLkJ1c1JlcGx5IgASOQoHUG9sbFNydhIVLk1z",
            "Z1JwY0J1cy5CdXNSZXF1ZXN0GhMuTXNnUnBjQnVzLkJ1c1JlcGx5IgAwARI5",
            "CgdQdXNoU3J2EhUuTXNnUnBjQnVzLkJ1c1JlcXVlc3QaEy5Nc2dScGNCdXMu",
            "QnVzUmVwbHkiACgBEjsKB0NoYXRTcnYSFS5Nc2dScGNCdXMuQnVzUmVxdWVz",
            "dBoTLk1zZ1JwY0J1cy5CdXNSZXBseSIAKAEwAUIKqgIHZ1JwY0J1c2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::gRpcBus.BusRequest), global::gRpcBus.BusRequest.Parser, new[]{ "Name", "Active", "Id", "ReqJson", "ReqBytes", "Args", "Version" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::gRpcBus.BusReply), global::gRpcBus.BusReply.Parser, new[]{ "Id", "Reqid", "RspJson", "RspBytes", "Args", "Version" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BusRequest : pb::IMessage<BusRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BusRequest> _parser = new pb::MessageParser<BusRequest>(() => new BusRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BusRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::gRpcBus.RpcBusReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BusRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BusRequest(BusRequest other) : this() {
      name_ = other.name_;
      active_ = other.active_;
      id_ = other.id_;
      reqJson_ = other.reqJson_.Clone();
      reqBytes_ = other.reqBytes_.Clone();
      args_ = other.args_.Clone();
      version_ = other.version_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BusRequest Clone() {
      return new BusRequest(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "active" field.</summary>
    public const int ActiveFieldNumber = 2;
    private string active_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Active {
      get { return active_; }
      set {
        active_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 3;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "ReqJson" field.</summary>
    public const int ReqJsonFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_reqJson_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> reqJson_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> ReqJson {
      get { return reqJson_; }
    }

    /// <summary>Field number for the "ReqBytes" field.</summary>
    public const int ReqBytesFieldNumber = 5;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_reqBytes_codec
        = pb::FieldCodec.ForBytes(42);
    private readonly pbc::RepeatedField<pb::ByteString> reqBytes_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<pb::ByteString> ReqBytes {
      get { return reqBytes_; }
    }

    /// <summary>Field number for the "Args" field.</summary>
    public const int ArgsFieldNumber = 6;
    private static readonly pbc::MapField<string, string>.Codec _map_args_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 50);
    private readonly pbc::MapField<string, string> args_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Args {
      get { return args_; }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 7;
    private string version_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Version {
      get { return version_; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BusRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BusRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Active != other.Active) return false;
      if (Id != other.Id) return false;
      if(!reqJson_.Equals(other.reqJson_)) return false;
      if(!reqBytes_.Equals(other.reqBytes_)) return false;
      if (!Args.Equals(other.Args)) return false;
      if (Version != other.Version) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Active.Length != 0) hash ^= Active.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      hash ^= reqJson_.GetHashCode();
      hash ^= reqBytes_.GetHashCode();
      hash ^= Args.GetHashCode();
      if (Version.Length != 0) hash ^= Version.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Active.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Active);
      }
      if (Id != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Id);
      }
      reqJson_.WriteTo(output, _repeated_reqJson_codec);
      reqBytes_.WriteTo(output, _repeated_reqBytes_codec);
      args_.WriteTo(output, _map_args_codec);
      if (Version.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Version);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Active.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Active);
      }
      if (Id != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Id);
      }
      reqJson_.WriteTo(ref output, _repeated_reqJson_codec);
      reqBytes_.WriteTo(ref output, _repeated_reqBytes_codec);
      args_.WriteTo(ref output, _map_args_codec);
      if (Version.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Version);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Active.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Active);
      }
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      size += reqJson_.CalculateSize(_repeated_reqJson_codec);
      size += reqBytes_.CalculateSize(_repeated_reqBytes_codec);
      size += args_.CalculateSize(_map_args_codec);
      if (Version.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BusRequest other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Active.Length != 0) {
        Active = other.Active;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      reqJson_.Add(other.reqJson_);
      reqBytes_.Add(other.reqBytes_);
      args_.Add(other.args_);
      if (other.Version.Length != 0) {
        Version = other.Version;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Active = input.ReadString();
            break;
          }
          case 24: {
            Id = input.ReadInt32();
            break;
          }
          case 34: {
            reqJson_.AddEntriesFrom(input, _repeated_reqJson_codec);
            break;
          }
          case 42: {
            reqBytes_.AddEntriesFrom(input, _repeated_reqBytes_codec);
            break;
          }
          case 50: {
            args_.AddEntriesFrom(input, _map_args_codec);
            break;
          }
          case 58: {
            Version = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Active = input.ReadString();
            break;
          }
          case 24: {
            Id = input.ReadInt32();
            break;
          }
          case 34: {
            reqJson_.AddEntriesFrom(ref input, _repeated_reqJson_codec);
            break;
          }
          case 42: {
            reqBytes_.AddEntriesFrom(ref input, _repeated_reqBytes_codec);
            break;
          }
          case 50: {
            args_.AddEntriesFrom(ref input, _map_args_codec);
            break;
          }
          case 58: {
            Version = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class BusReply : pb::IMessage<BusReply>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BusReply> _parser = new pb::MessageParser<BusReply>(() => new BusReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BusReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::gRpcBus.RpcBusReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BusReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BusReply(BusReply other) : this() {
      id_ = other.id_;
      reqid_ = other.reqid_;
      rspJson_ = other.rspJson_.Clone();
      rspBytes_ = other.rspBytes_.Clone();
      args_ = other.args_.Clone();
      version_ = other.version_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BusReply Clone() {
      return new BusReply(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "reqid" field.</summary>
    public const int ReqidFieldNumber = 2;
    private int reqid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Reqid {
      get { return reqid_; }
      set {
        reqid_ = value;
      }
    }

    /// <summary>Field number for the "RspJson" field.</summary>
    public const int RspJsonFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_rspJson_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> rspJson_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> RspJson {
      get { return rspJson_; }
    }

    /// <summary>Field number for the "RspBytes" field.</summary>
    public const int RspBytesFieldNumber = 4;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_rspBytes_codec
        = pb::FieldCodec.ForBytes(34);
    private readonly pbc::RepeatedField<pb::ByteString> rspBytes_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<pb::ByteString> RspBytes {
      get { return rspBytes_; }
    }

    /// <summary>Field number for the "Args" field.</summary>
    public const int ArgsFieldNumber = 5;
    private static readonly pbc::MapField<string, string>.Codec _map_args_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 42);
    private readonly pbc::MapField<string, string> args_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Args {
      get { return args_; }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 7;
    private string version_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Version {
      get { return version_; }
      set {
        version_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BusReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BusReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Reqid != other.Reqid) return false;
      if(!rspJson_.Equals(other.rspJson_)) return false;
      if(!rspBytes_.Equals(other.rspBytes_)) return false;
      if (!Args.Equals(other.Args)) return false;
      if (Version != other.Version) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Reqid != 0) hash ^= Reqid.GetHashCode();
      hash ^= rspJson_.GetHashCode();
      hash ^= rspBytes_.GetHashCode();
      hash ^= Args.GetHashCode();
      if (Version.Length != 0) hash ^= Version.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Reqid != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Reqid);
      }
      rspJson_.WriteTo(output, _repeated_rspJson_codec);
      rspBytes_.WriteTo(output, _repeated_rspBytes_codec);
      args_.WriteTo(output, _map_args_codec);
      if (Version.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Version);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Reqid != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Reqid);
      }
      rspJson_.WriteTo(ref output, _repeated_rspJson_codec);
      rspBytes_.WriteTo(ref output, _repeated_rspBytes_codec);
      args_.WriteTo(ref output, _map_args_codec);
      if (Version.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Version);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Reqid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Reqid);
      }
      size += rspJson_.CalculateSize(_repeated_rspJson_codec);
      size += rspBytes_.CalculateSize(_repeated_rspBytes_codec);
      size += args_.CalculateSize(_map_args_codec);
      if (Version.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Version);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BusReply other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Reqid != 0) {
        Reqid = other.Reqid;
      }
      rspJson_.Add(other.rspJson_);
      rspBytes_.Add(other.rspBytes_);
      args_.Add(other.args_);
      if (other.Version.Length != 0) {
        Version = other.Version;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Reqid = input.ReadInt32();
            break;
          }
          case 26: {
            rspJson_.AddEntriesFrom(input, _repeated_rspJson_codec);
            break;
          }
          case 34: {
            rspBytes_.AddEntriesFrom(input, _repeated_rspBytes_codec);
            break;
          }
          case 42: {
            args_.AddEntriesFrom(input, _map_args_codec);
            break;
          }
          case 58: {
            Version = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Reqid = input.ReadInt32();
            break;
          }
          case 26: {
            rspJson_.AddEntriesFrom(ref input, _repeated_rspJson_codec);
            break;
          }
          case 34: {
            rspBytes_.AddEntriesFrom(ref input, _repeated_rspBytes_codec);
            break;
          }
          case 42: {
            args_.AddEntriesFrom(ref input, _map_args_codec);
            break;
          }
          case 58: {
            Version = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
