// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RpcBus.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace gRpcBus {
  public static partial class RpcBus
  {
    static readonly string __ServiceName = "MsgRpcBus.RpcBus";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::gRpcBus.BusRequest> __Marshaller_MsgRpcBus_BusRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRpcBus.BusRequest.Parser));
    static readonly grpc::Marshaller<global::gRpcBus.BusReply> __Marshaller_MsgRpcBus_BusReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRpcBus.BusReply.Parser));

    static readonly grpc::Method<global::gRpcBus.BusRequest, global::gRpcBus.BusReply> __Method_RequestSrv = new grpc::Method<global::gRpcBus.BusRequest, global::gRpcBus.BusReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RequestSrv",
        __Marshaller_MsgRpcBus_BusRequest,
        __Marshaller_MsgRpcBus_BusReply);

    static readonly grpc::Method<global::gRpcBus.BusRequest, global::gRpcBus.BusReply> __Method_PollSrv = new grpc::Method<global::gRpcBus.BusRequest, global::gRpcBus.BusReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "PollSrv",
        __Marshaller_MsgRpcBus_BusRequest,
        __Marshaller_MsgRpcBus_BusReply);

    static readonly grpc::Method<global::gRpcBus.BusRequest, global::gRpcBus.BusReply> __Method_PushSrv = new grpc::Method<global::gRpcBus.BusRequest, global::gRpcBus.BusReply>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "PushSrv",
        __Marshaller_MsgRpcBus_BusRequest,
        __Marshaller_MsgRpcBus_BusReply);

    static readonly grpc::Method<global::gRpcBus.BusRequest, global::gRpcBus.BusReply> __Method_ChatSrv = new grpc::Method<global::gRpcBus.BusRequest, global::gRpcBus.BusReply>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "ChatSrv",
        __Marshaller_MsgRpcBus_BusRequest,
        __Marshaller_MsgRpcBus_BusReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::gRpcBus.RpcBusReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RpcBus</summary>
    [grpc::BindServiceMethod(typeof(RpcBus), "BindService")]
    public abstract partial class RpcBusBase
    {
      public virtual global::System.Threading.Tasks.Task<global::gRpcBus.BusReply> RequestSrv(global::gRpcBus.BusRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task PollSrv(global::gRpcBus.BusRequest request, grpc::IServerStreamWriter<global::gRpcBus.BusReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::gRpcBus.BusReply> PushSrv(grpc::IAsyncStreamReader<global::gRpcBus.BusRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task ChatSrv(grpc::IAsyncStreamReader<global::gRpcBus.BusRequest> requestStream, grpc::IServerStreamWriter<global::gRpcBus.BusReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RpcBus</summary>
    public partial class RpcBusClient : grpc::ClientBase<RpcBusClient>
    {
      /// <summary>Creates a new client for RpcBus</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RpcBusClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RpcBus that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RpcBusClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RpcBusClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RpcBusClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::gRpcBus.BusReply RequestSrv(global::gRpcBus.BusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RequestSrv(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::gRpcBus.BusReply RequestSrv(global::gRpcBus.BusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RequestSrv, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::gRpcBus.BusReply> RequestSrvAsync(global::gRpcBus.BusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RequestSrvAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::gRpcBus.BusReply> RequestSrvAsync(global::gRpcBus.BusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RequestSrv, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::gRpcBus.BusReply> PollSrv(global::gRpcBus.BusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PollSrv(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::gRpcBus.BusReply> PollSrv(global::gRpcBus.BusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_PollSrv, null, options, request);
      }
      public virtual grpc::AsyncClientStreamingCall<global::gRpcBus.BusRequest, global::gRpcBus.BusReply> PushSrv(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PushSrv(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::gRpcBus.BusRequest, global::gRpcBus.BusReply> PushSrv(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_PushSrv, null, options);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::gRpcBus.BusRequest, global::gRpcBus.BusReply> ChatSrv(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ChatSrv(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::gRpcBus.BusRequest, global::gRpcBus.BusReply> ChatSrv(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_ChatSrv, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RpcBusClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RpcBusClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(RpcBusBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RequestSrv, serviceImpl.RequestSrv)
          .AddMethod(__Method_PollSrv, serviceImpl.PollSrv)
          .AddMethod(__Method_PushSrv, serviceImpl.PushSrv)
          .AddMethod(__Method_ChatSrv, serviceImpl.ChatSrv).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RpcBusBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RequestSrv, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::gRpcBus.BusRequest, global::gRpcBus.BusReply>(serviceImpl.RequestSrv));
      serviceBinder.AddMethod(__Method_PollSrv, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::gRpcBus.BusRequest, global::gRpcBus.BusReply>(serviceImpl.PollSrv));
      serviceBinder.AddMethod(__Method_PushSrv, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::gRpcBus.BusRequest, global::gRpcBus.BusReply>(serviceImpl.PushSrv));
      serviceBinder.AddMethod(__Method_ChatSrv, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::gRpcBus.BusRequest, global::gRpcBus.BusReply>(serviceImpl.ChatSrv));
    }

  }
}
#endregion
